# src/main/resources/application.yml

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/studysync
    username: postgres
    password: postgres  # Replace with your PostgreSQL password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update  # Change to 'validate' once you have Flyway migrations
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

server:
  port: 9000
  servlet:
    context-path: /api

logging:
  level:
    org.springframework: INFO
    com.studysync: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE